import type { SearchResult } from "./workflow"

interface ScoutNotificationPayload {
  scoutId: string
  scoutName: string
  query: string
  newResults: SearchResult[]
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

function formatEmailHtml(payload: ScoutNotificationPayload): string {
  const listItems = payload.newResults
    .slice(0, 10)
    .map(
      (r) =>
        `<li><a href="${escapeHtml(r.url)}">${escapeHtml(r.title || r.url)}</a><br/><small>${escapeHtml(
          r.snippet || ""
        )}</small></li>`
    )
    .join("")

  return `
<!DOCTYPE html>
<html>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 16px;">
  <h2 style="margin: 0 0 8px 0;">New scout findings: ${escapeHtml(payload.scoutName)}</h2>
  <p style="color: #666; margin: 0 0 12px 0;">Query: ${escapeHtml(payload.query)}</p>
  <p style="margin: 0 0 12px 0;">${payload.newResults.length} new results found.</p>
  <ol style="padding-left: 20px; color: #333;">${listItems}</ol>
  <p style="color: #999; font-size: 12px;">Top 10 shown. Generated by Daedalus Scout.</p>
</body>
</html>`
}

export async function sendScoutEmailNotification(
  email: string,
  payload: ScoutNotificationPayload
): Promise<boolean> {
  const resendApiKey = process.env.RESEND_API_KEY
  if (!resendApiKey) {
    console.log("[scout] Notification skipped: RESEND_API_KEY not configured")
    return false
  }

  try {
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${resendApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: process.env.RESEND_FROM_EMAIL || "notifications@resend.dev",
        to: email,
        subject: `[Daedalus] New scout findings for ${payload.scoutName}`,
        html: formatEmailHtml(payload),
      }),
    })

    if (!response.ok) {
      const errorText = await response.text()
      console.error("[scout] Email send failed:", errorText)
      return false
    }

    return true
  } catch (error) {
    console.error("[scout] Notification error:", error)
    return false
  }
}
