import {escapeHtml} from '@/platform/notifications/types'

export interface ScoutTemplateResult {
  url: string
  title: string | null
  snippet: string | null
}

export interface ScoutEmailTemplatePayload {
  scoutName: string
  query: string
  newResults: ScoutTemplateResult[]
}

export function renderScoutEmailHtml(payload: ScoutEmailTemplatePayload): string {
  const listItems = payload.newResults
    .slice(0, 10)
    .map(
      (result) =>
        `<li><a href="${escapeHtml(result.url)}">${escapeHtml(result.title || result.url)}</a><br/><small>${escapeHtml(result.snippet || '')}</small></li>`
    )
    .join('')

  return `
<!DOCTYPE html>
<html>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 16px;">
  <h2 style="margin: 0 0 8px 0;">New scout findings: ${escapeHtml(payload.scoutName)}</h2>
  <p style="color: #666; margin: 0 0 12px 0;">Query: ${escapeHtml(payload.query)}</p>
  <p style="margin: 0 0 12px 0;">${payload.newResults.length} new results found.</p>
  <ol style="padding-left: 20px; color: #333;">${listItems}</ol>
  <p style="color: #999; font-size: 12px;">Top 10 shown. Generated by Daedalus Scout.</p>
</body>
</html>`
}
