import type { RadarEvent, RadarRule } from "./types"

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

function renderEmailHtml(rule: RadarRule, events: RadarEvent[]): string {
  const items = events
    .slice(0, 10)
    .map(
      (e) =>
        `<li style="margin-bottom:12px;"><strong>${escapeHtml(e.source)}</strong> — <a href="${escapeHtml(
          e.url
        )}">${escapeHtml(e.title || e.url)}</a><br/><small>${escapeHtml(e.snippet || "")}</small><br/><small>Matched: ${escapeHtml(
          e.matched_terms.join(", ")
        )}</small></li>`
    )
    .join("")

  return `
<!DOCTYPE html>
<html>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 16px;">
  <h2 style="margin: 0 0 8px 0;">Radar alerts: ${escapeHtml(rule.name)}</h2>
  <p style="color:#666; margin: 0 0 12px 0;">${events.length} new mentions.</p>
  <ol style="padding-left: 20px;">${items}</ol>
  <p style="color:#999; font-size: 12px;">Top 10 shown. Generated by Daedalus Radar.</p>
</body>
</html>`
}

export async function sendRadarEmail(rule: RadarRule, events: RadarEvent[]): Promise<boolean> {
  const apiKey = process.env.RESEND_API_KEY
  if (!apiKey || !rule.notify_email) {
    console.log("[radar] Email skipped: missing RESEND_API_KEY or notify_email")
    return false
  }

  try {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: process.env.RESEND_FROM_EMAIL || "notifications@resend.dev",
        to: rule.notify_email,
        subject: `[Radar] ${events.length} new mentions for ${rule.name}`,
        html: renderEmailHtml(rule, events),
      }),
    })

    if (!res.ok) {
      const text = await res.text()
      console.error("[radar] Email send failed", text)
      return false
    }
    return true
  } catch (error) {
    console.error("[radar] Email error", error)
    return false
  }
}

export async function sendRadarWebhook(rule: RadarRule, events: RadarEvent[]): Promise<boolean> {
  if (!rule.notify_webhook) return false
  try {
    const res = await fetch(rule.notify_webhook, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        event: "radar.alert",
        rule_id: rule.id,
        rule_name: rule.name,
        count: events.length,
        mentions: events.slice(0, 20).map((e) => ({
          source: e.source,
          url: e.url,
          title: e.title,
          snippet: e.snippet,
          matched_terms: e.matched_terms,
          occurred_at: e.occurred_at,
        })),
      }),
    })
    return res.ok
  } catch (error) {
    console.error("[radar] Webhook error", error)
    return false
  }
}
